;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-delete-char
	evil-forward-char
	evil-insert
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-undo
	))

(setq mc/cmds-to-run-once
      '(
	evil-delete-backward-char-and-join
	evil-find-char
	evil-force-normal-state
	evil-inner-back-quote
	evil-ret
	org-kill-line
	org-self-insert-command
	))
